### ISSUE TITLE
C# example doesn't work on VS2015/Win10 with 64bit DLL

### ISSUE THREAD

**Issue by DeadSix27** [mpv-player/mpv-examples#4]
Solved
_____
Tried compiling the example, compiles fine, however the "video never plays"

Any idea? (tried a precompiled mpv-1.dll and my own build)

No errors either, at least none that I can see. the DLL however loads fine.
Gets up to:
DoMpvCommand("loadfile", textBoxVideoSampleFileName.Text);
and does NOT crash, it just.. seems to do nothing.
Anything I'm doing wrong?

(Also tried it with WPF and a WindowsFormsHost, not that that would make a difference)

**Comment by FlyingCircus-** [comment]
Hello there @DeadSix27.
I had never been able to use the precompiled mpv-1.dll for x64 in the C# example. I only could make it work using the 32-bit components, this is: downloading the "dev" and "32-bit" sources from https://mpv.srsfckn.biz/ and using the mpv-1.dll from the "dev/32" folder and the d3dcompiler_43.dll from the "32-bit" source.

I wonder if you made it work with the x64 version instead, and in such a case what dependencies you used, because copying everything from the sources doesn't work for me.

**Comment by lachs0r** [comment]
I don’t have MSVS right now but make sure your project configuration is for x64 native builds.

**Comment by FlyingCircus-** [comment]
@lachs0r You're right, I'm really nooby at this. I configured the project for x64 (in SharpDevelop) and everything went fine
