### ISSUE TITLE
Sorry to bother, some help needed

### ISSUE THREAD

**Issue by FlyingCircus-** [mpv-player/mpv-examples#5]
Hi there. I'm looking at mpv-examples/libmpv/csharp for a way to implement the player using winforms. The code executes but it doesn't seem to play any media file. If I add up the last version of mpv-1.dll inside the build location I get a blue screen inside the picturebox when opening a media file, although it still doesn't play anything.

I know I'm doing something wrong since I'm fairly unexperienced at this. Any advice to make it work?

**Comment by wm4** [comment]
CC @niksedk  @rossy

**Comment by niksedk** [comment]
It seems this commit gives the blue screen: https://github.com/mpv-player/mpv-examples/commit/0cfb5ea45df16999ae8a94e61d9fcb860f18713e
To make it work, just add this line again: `_mpvSetOptionString(_mpvHandle, GetUtf8Bytes("vo"), GetUtf8Bytes("direct3d"));`
(also, sometimes video will not display when debugging with visual studio)

@rossy: Apparently mpv cannot pick a default "Video Output driver", so what is the correct way of doing this? 
It would also be nice to have a dot net OpenGL sample...

**Comment by rossy** [comment]
Sorry for the late response. A common cause for the "blue screen" is a missing d3dcompiler_43.dll. It seems like this DLL is missing from the "Dev" packages on https://mpv.srsfckn.biz/, but it can be found inside the normal 32 and 64-bit builds. Unzipping it alongside mpv-1.dll should fix the problem. If you have Windows 8.1 or 10, you can also copy d3dcompiler_47.dll from your system32 directory and rename it to d3dcompiler_43.dll (the "version" of the DLL doesn't seem to matter.)

> Apparently libmpv cannot pick a default "Video Output driver", so what is the correct way of doing this?
> It would also be nice to have a dot net OpenGL sample...

I think mpv will fall back to --vo=direct3d if it can't create a suitable OpenGL context. In this case, I guess the problem is that mpv doesn't find out the OpenGL context is bad until it tries to create a shader and finds out that the shader compiler DLL is missing, at which point the OpenGL backend has already been chosen.

**Comment by niksedk** [comment]
I think we should add this line back again - perhaps with opengl as first choice:
` _mpvSetOptionString(_mpvHandle, GetUtf8Bytes("vo"), GetUtf8Bytes("opengl,direct3d"));`
See https://mpv.io/manual/stable#video-output-drivers
What do you think @rossy? (I cannot make it work without this line - can you?)
This code has also be really well tested via https://github.com/SubtitleEdit/subtitleedit

Off topic: "OpenGL embedding" with ODS control would be a nice sample -  https://github.com/mpv-player/mpv-examples/tree/master/libmpv#user-content-opengl-embedding

**Comment by FlyingCircus-** [comment]
Thank for all your replies. As @rossy suggested, the missing d3d3compiler_43.dll file solved my problem. I didn't have any trouble without the "_mpvSetOptionString..." line.
Keep up the good work guys.

**Comment by rossy** [comment]
@FlyingCircus- Nice. Glad it's fixed.

@niksedk Yeah, the OpenGL VO worked for me. Problem is, the Direct3D VO is not really recommended for normal use. It has poor performance and inaccurate rendering, and it should only be used as a last resort. The GL VO, however should work on all hardware that supports D3D feature level 9_3 or PS 3.0 (through ANGLE,) and for unsupported hardware, it should fall back to software rendering through WARP.

Are you getting the blue screen error or something else? Unfortunately this stuff is hard to debug, since the .NET example doesn't have a way to get log output (yet.) Depending on where you got your libmpv-1.dll, you might need to put d3dcompiler_47.dll or d3dcompiler_43.dll alongside it.

> Off topic: "OpenGL embedding" with ODS control would be a nice sample - https://github.com/mpv-player/mpv-examples/tree/master/libmpv#user-content-opengl-embedding

+1. Though it might be difficult to integrate libmpv with a managed OpenGL toolkit. It might require a more low-level solution.
